#!/usr/bin/env bash

set -eu

VERSION=1.0.0-5.4.0

docker pull docker.io/debian:9.5-slim
docker build -t docker.io/copla/physiological-networks-tds:${VERSION} .
docker run docker.io/copla/physiological-networks-tds:${VERSION} ccagent --version
docker push docker.io/copla/physiological-networks-tds:${VERSION}
